from dataclasses import dataclass
from typing import Optional
from matplotlib.colors import ListedColormap
import script.memorization.plots.palettes as palette

@dataclass(frozen=True)
class ModelInfo:
    path: str
    family: str
    size: str
    plot_name: str
    plot_color: Optional[tuple] = None       # color tuple from palette
    bar_style: Optional[str] = None          # hatch style
    cmap: Optional[ListedColormap] = None    # colormap from palette
    line_style: Optional[str] = None         # matplotlib linestyle

MODEL_INFO = {
    "pythia-1b": ModelInfo(
        path="EleutherAI/pythia-1b",
        family="pythia",
        size="1b",
        plot_name="Pythia 1B",
    ),
    "pythia-2.8b": ModelInfo(
        path="EleutherAI/pythia-2.8b",
        family="pythia",
        size="2.8b",
        plot_name="Pythia 2.8B",
    ),
    "pythia-6.9b": ModelInfo(
        path="EleutherAI/pythia-6.9b",
        family="pythia",
        size="6.9b",
        plot_name="Pythia 6.9B",
        plot_color=palette.pythia_palette[200],
        bar_style=palette.small_hatch,
        cmap=palette.pythia_cmap,
    ),
    "pythia-12b": ModelInfo(
        path="EleutherAI/pythia-12b",
        family="pythia",
        size="12b",
        plot_name="Pythia 12B",
        plot_color=palette.pythia_palette[400],
        bar_style=palette.medium_hatch,
        cmap=palette.pythia_cmap,
        line_style='-',
    ),
    "huggyllama-7b": ModelInfo(
        path="huggyllama/llama-7b",
        family="huggyllama",
        size="7b",
        plot_name="Llama 1 7B",
        plot_color=palette.llama1_palette[200],
        bar_style=palette.small_hatch,
        cmap=palette.llama1_cmap,
        line_style='-.',
    ),
    "huggyllama-13b": ModelInfo(
        path="huggyllama/llama-13b",
        family="huggyllama",
        size="13b",
        plot_name="Llama 1 13B",
        plot_color=palette.llama1_palette[400],
        bar_style=palette.medium_hatch,
        cmap=palette.llama1_cmap,
        line_style='-',
    ),
    "huggyllama-30b": ModelInfo(
        path="huggyllama/llama-30b",
        family="huggyllama",
        size="30b",
        plot_name="Llama 1 30B",
        plot_color=palette.llama1_palette[600],
        bar_style=palette.small_hatch,
        line_style=':',
    ),
    "huggyllama-65b": ModelInfo(
        path="huggyllama/llama-65b",
        family="huggyllama",
        size="65b",
        plot_name="Llama 1 65B",
        plot_color=palette.llama1_palette[800],
        bar_style=palette.large_hatch,
        cmap=palette.llama1_cmap,
        line_style='--',
    ),
    "Llama-2-7b": ModelInfo(
        path="meta-llama/Llama-2-7b-hf",
        family="llama-2",
        size="7b",
        plot_name="Llama 2 7B",
        plot_color=palette.llama2_palette[200],
        bar_style=palette.small_hatch,
        cmap=palette.llama2_cmap,
    ),
    "Llama-2-13b": ModelInfo(
        path="meta-llama/Llama-2-13b-hf",
        family="llama-2",
        size="13b",
        plot_name="Llama 2 13B",
        plot_color=palette.llama2_palette[400],
        bar_style=palette.medium_hatch,
        cmap=palette.llama2_cmap,
    ),
    "Llama-2-70b": ModelInfo(
        path="meta-llama/Llama-2-70b-hf",
        family="llama-2",
        size="70b",
        plot_name="Llama 2 70B",
        plot_color=palette.llama2_palette[800],
        bar_style=palette.large_hatch,
        cmap=palette.llama2_cmap,
    ),
    "Llama-3-8b": ModelInfo(
        path="meta-llama/Meta-Llama-3-8B",
        family="llama-3",
        size="8b",
        plot_name="Llama 3 8B",
        plot_color=palette.llama3_palette[200],
        bar_style=palette.small_hatch,
        cmap=palette.llama3_cmap,
    ),
    "Llama-3-70b": ModelInfo(
        path="meta-llama/Meta-Llama-3-70B",
        family="llama-3",
        size="70b",
        plot_name="Llama 3 70B",
        plot_color=palette.llama3_palette[800],
        bar_style=palette.large_hatch,
        cmap=palette.llama3_cmap,
    ),
    "Llama-3.1-8b": ModelInfo(
        path="meta-llama/Llama-3.1-8B",
        family="llama-3.1",
        size="8b",
        plot_name="Llama 3.1 8B",
        plot_color=palette.llama3_palette[200],
        bar_style=palette.small_hatch,
        cmap=palette.llama3_cmap,
    ),
    "Llama-3.1-70b": ModelInfo(
        path="meta-llama/Llama-3.1-70B",
        family="llama-3.1",
        size="70b",
        plot_name="Llama 3.1 70B",
        plot_color=palette.llama3_palette[800],
        bar_style=palette.large_hatch,
        cmap=palette.llama3_cmap,
    ),
    "phi-4": ModelInfo(
        path="microsoft/phi-4",
        family="phi",
        size="14b",
        plot_name="Phi 4",
        plot_color=palette.phi_palette[400],
        bar_style=palette.medium_hatch,
        cmap=palette.phi_cmap,
        line_style='-',
    ),
    "deepseek-1-7b": ModelInfo(
        path="deepseek-ai/deepseek-llm-7b-base",
        family="deepseek-1",
        size="7b",
        plot_name="DeepSeek v1 7B",
        plot_color=palette.ds_palette[200],
        bar_style=palette.small_hatch,
        cmap=palette.ds_cmap,
    ),
    "deepseek-1-67b": ModelInfo(
        path="deepseek-ai/deepseek-llm-67b-base",
        family="deepseek-1",
        size="67b",
        plot_name="DeepSeek v1 67B",
        plot_color=palette.ds_palette[800],
        bar_style=palette.large_hatch,
        cmap=palette.ds_cmap,
    ),
    "gemma-2-2b": ModelInfo(
        path="google/gemma-2-2b",
        family="gemma-2",
        size="2b",
        plot_name="Gemma 2 2B",
        plot_color=palette.gemma2_palette[10],
        bar_style=palette.small_hatch,
        cmap=palette.gemma2_cmap,
    ),
    "gemma-2-9b": ModelInfo(
        path="google/gemma-2-9b",
        family="gemma-2",
        size="9b",
        plot_name="Gemma 2 9B",
        plot_color=palette.gemma2_palette[200],
        bar_style=palette.medium_hatch,
        cmap=palette.gemma2_cmap,
    ),
    "gemma-2-27b": ModelInfo(
        path="google/gemma-2-27b",
        family="gemma-2",
        size="27b",
        plot_name="Gemma 2 27B",
        plot_color=palette.gemma2_palette[600],
        bar_style=palette.large_hatch,
        cmap=palette.gemma2_cmap,
    ),
    "Qwen-2.5-72b": ModelInfo(
        path="Qwen/Qwen2.5-72B",
        family="Qwen2.5",
        size="72b",
        plot_name="Qwen 2.5 72B",
        plot_color=palette.qwen_palette[800],
        bar_style=palette.large_hatch,
        cmap=palette.qwen_cmap,
    ),
}
